/*
 *  OpenBangla Keyboard
 *  Copyright (C) 2016 Muhammad Mominul Huque <mominul2082@gmail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <QApplication>
#include <QMessageBox>
#include <QCommandLineParser>
#include <QCommandLineOption>
#include <QFile>
#include <QTextStream>
#include <QDir>
#include "TopBar.h"
#include "SingleInstance.h"
#include "Settings.h"
#include "FileSystem.h"

int main(int argc, char *argv[]) {  
  QApplication app(argc, argv);

  // Load custom theme stylesheet if generated by Matugen (wallpaper color matching)
  QString userStylePath = QDir::homePath() + "/.config/openbangla-keyboard/style.qss";
  QFile userStyleFile(userStylePath);
  if (userStyleFile.open(QFile::ReadOnly | QFile::Text)) {
    QTextStream ts(&userStyleFile);
    app.setStyleSheet(ts.readAll());
  } else {
    // Fall back to standard modern Material Dark stylesheet
    app.setStyleSheet(
      "QWidget {"
      "    color: #E0E0E0;"
      "    font-family: 'Segoe UI', 'Roboto', 'Inter', sans-serif;"
      "    font-size: 13px;"
      "}"
      "QDialog {"
      "    background-color: #121212;"
      "}"
      "QGroupBox {"
      "    background-color: #1A1A1A;"
      "    border: 1px solid #2D2D2D;"
      "    border-radius: 8px;"
      "    margin-top: 1.5em;"
      "    padding: 16px;"
      "    font-weight: bold;"
      "}"
      "QGroupBox::title {"
      "    subcontrol-origin: margin;"
      "    subcontrol-position: top left;"
      "    left: 10px;"
      "    padding: 0 5px;"
      "    color: #2196F3;"
      "}"
      "QPushButton {"
      "    background-color: #2D2D2D;"
      "    border: 1px solid #3D3D3D;"
      "    border-radius: 6px;"
      "    color: #FFFFFF;"
      "    padding: 6px 16px;"
      "    min-height: 20px;"
      "}"
      "QPushButton:hover {"
      "    background-color: #3D3D3D;"
      "    border-color: #4D4D4D;"
      "}"
      "QPushButton:pressed {"
      "    background-color: #1A1A1A;"
      "}"
      "QPushButton:checked {"
      "    background-color: #2196F3;"
      "    color: #FFFFFF;"
      "    border: 1px solid #1976D2;"
      "}"
      "QPushButton:checked:hover {"
      "    background-color: #1E88E5;"
      "}"
      "QPushButton#btnCancel {"
      "    background-color: transparent;"
      "    border: 1px solid #3D3D3D;"
      "}"
      "QPushButton#btnCancel:hover {"
      "    background-color: rgba(255, 255, 255, 0.05);"
      "}"
      "QPushButton#btnOK {"
      "    background-color: #2196F3;"
      "    border: 1px solid #1976D2;"
      "    color: #FFFFFF;"
      "}"
      "QPushButton#btnOK:hover {"
      "    background-color: #1E88E5;"
      "}"
      "QPushButton#btnOK:pressed {"
      "    background-color: #1565C0;"
      "}"
      "QComboBox {"
      "    background-color: #1A1A1A;"
      "    border: 1px solid #2D2D2D;"
      "    border-radius: 6px;"
      "    padding: 5px 10px;"
      "    min-width: 6em;"
      "    color: #E0E0E0;"
      "}"
      "QComboBox:hover {"
      "    border-color: #2196F3;"
      "}"
      "QComboBox::drop-down {"
      "    subcontrol-origin: padding;"
      "    subcontrol-position: top right;"
      "    width: 20px;"
      "    border-left-width: 0px;"
      "}"
      "QComboBox QAbstractItemView {"
      "    background-color: #1A1A1A;"
      "    border: 1px solid #2D2D2D;"
      "    selection-background-color: #2196F3;"
      "    selection-color: #FFFFFF;"
      "    color: #E0E0E0;"
      "}"
      "QLabel {"
      "    color: #B0B0B0;"
      "}"
      "QLineEdit {"
      "    background-color: #1A1A1A;"
      "    border: 1px solid #2D2D2D;"
      "    border-radius: 6px;"
      "    padding: 6px;"
      "    color: #FFFFFF;"
      "}"
      "QLineEdit:focus {"
      "    border: 1px solid #2196F3;"
      "}"
      "QTreeView {"
      "    background-color: #1A1A1A;"
      "    border: 1px solid #2D2D2D;"
      "    border-radius: 6px;"
      "    color: #E0E0E0;"
      "}"
      "QTreeView::item {"
      "    padding: 6px;"
      "}"
      "QTreeView::item:hover {"
      "    background-color: #2D2D2D;"
      "}"
      "QTreeView::item:selected {"
      "    background-color: #2196F3;"
      "    color: #FFFFFF;"
      "}"
      "QHeaderView::section {"
      "    background-color: #2D2D2D;"
      "    color: #FFFFFF;"
      "    padding: 6px;"
      "    border: 1px solid #2D2D2D;"
      "}"
      "QScrollBar:vertical {"
      "    background-color: #121212;"
      "    width: 10px;"
      "    margin: 0px;"
      "}"
      "QScrollBar::handle:vertical {"
      "    background-color: #2D2D2D;"
      "    min-height: 20px;"
      "    border-radius: 5px;"
      "}"
      "QScrollBar::handle:vertical:hover {"
      "    background-color: #2196F3;"
      "}"
      "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
      "    background: none;"
      "    height: 0px;"
      "}"
    );
  }

  gUserFolders = new UserFolders();
  gSettings = new Settings();

  app.setApplicationName("OpenBangla Keyboard");
  app.setApplicationVersion(PROJECT_VERSION);

  QCommandLineParser parser;
  parser.setApplicationDescription("OpenBangla Keyboard");
  parser.addHelpOption();
  parser.addVersionOption();
  QCommandLineOption darkIcon("dark","Enable dark theme support");
  QCommandLineOption startInTray("tray","Start in tray");
  parser.addOption(darkIcon);
  parser.addOption(startInTray);
  parser.process(app);

  // Prevent many instances of the app to be launched
  QString name = "com.openbangla.keyboard";
  SingleInstance instance;
  if (instance.hasPrevious(name)) {
    QMessageBox msgBox(QMessageBox::Information,
                       "OpenBangla Keyboard",
                       "OpenBangla Keyboard is already running on this system and\nrunning more than one instance is not allowed.",
                       QMessageBox::Ok);
    msgBox.exec();
    return 0;
  }

  instance.listen(name);

  // Detect Dark Mode
  QPalette palette = app.palette();
  QColor color = palette.color(QPalette::Button);
  QColor darker = QColor::fromRgb(55, 55, 55); // Grayish color used for button in dark mode

  bool darkMode = (color == darker) || parser.isSet(darkIcon);

  TopBar w(darkMode);
  if (parser.isSet(startInTray))
    app.setProperty("invokedAsTray", parser.isSet(startInTray));
  else if(gSettings->getTopBarVisibility())
    w.show();

  app.setQuitOnLastWindowClosed(false);
  return app.exec();
}
